# download data

In [1]:
import pandas as pd
# website = https://celestrak.org/NORAD/elements/
oneweb_url = (
    "https://celestrak.org/NORAD/elements/"
    "gp.php?GROUP=ONEWEB&FORMAT=CSV"
)

oneweb_df = pd.read_csv(oneweb_url)

oneweb_df.head()

,OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT
0,ONEWEB-0012,2019-010A,2026-09-15T07:25:47.057088,13.165933,0.000248,87.9136,210.8870,85.9127,274.2287,0,U,44057,999,36342,0.000265,1.140000e-06,0
1,ONEWEB-0010,2019-010B,2026-09-15T20:48:18.667872,13.165932,0.000192,87.9148,210.7767,69.8134,290.3202,0,U,44058,999,36354,0.000187,8.400000e-07,0
2,ONEWEB-0008,2019-010C,2026-09-15T14:07:03.123840,13.165935,0.000191,87.9146,210.8262,90.5607,269.5743,0,U,44059,999,36362,-0.000094,-2.300000e-07,0
3,ONEWEB-0007,2019-010D,2026-09-15T22:09:34.634592,13.155480,0.000221,87.8974,241.1262,79.7005,280.4375,0,U,44060,999,36330,-0.000042,-3.000000e-08,0
4,ONEWEB-0006,2019-010E,2026-09-15T22:15:15.706368,13.155502,0.000184,87.8984,241.0992,83.6540,276.4800,0,U,44061,999,36335,0.000107,5.300000e-07,0

In [2]:
print("Number of satellites:", oneweb_df.shape[0])
print("Number of columns:", oneweb_df.shape[1])

Number of satellites: 651
Number of columns: 17

In [3]:
print(oneweb_df.columns.tolist())

['OBJECT_NAME', 'OBJECT_ID', 'EPOCH', 'MEAN_MOTION', 'ECCENTRICITY', 'INCLINATION', 'RA_OF_ASC_NODE', 'ARG_OF_PERICENTER', 'MEAN_ANOMALY', 'EPHEMERIS_TYPE', 'CLASSIFICATION_TYPE', 'NORAD_CAT_ID', 'ELEMENT_SET_NO', 'REV_AT_EPOCH', 'BSTAR', 'MEAN_MOTION_DOT', 'MEAN_MOTION_DDOT']

Important columns

OBJECT_NAME-        Satellite name
NORAD_CAT_ID-	    Unique satellite catalogue number
EPOCH-	            Time when the orbital data was calculated
INCLINATION	-       Orbital inclination in degrees
ECCENTRICITY-	    Shape of the orbit
MEAN_MOTION	-       Number of orbits per day
RA_OF_ASC_NODE-	    Orientation of the orbital plane
ARG_OF_PERICENTER-	Orientation within the orbit
MEAN_ANOMALY-	    Satellite position within its orbit
BSTAR-	            Atmospheric-drag-related parameter

In [4]:
oneweb_df.to_csv(
    "data/oneweb_satellites.csv",
    index=False
)

# startlink constellations

In [5]:
starlink_url = (
    "https://celestrak.org/NORAD/elements/"
    "gp.php?GROUP=STARLINK&FORMAT=CSV"
)

starlink_df = pd.read_csv(starlink_url)

# iridium NEXT Constellation

In [6]:
iridium_url = (
    "https://celestrak.org/NORAD/elements/"
    "gp.php?GROUP=IRIDIUM-NEXT&FORMAT=CSV"
)

iridium_df = pd.read_csv(iridium_url)

In [7]:
#combine all constellations
oneweb_df["CONSTELLATION"] = "OneWeb"
starlink_df["CONSTELLATION"] = "Starlink"
iridium_df["CONSTELLATION"] = "Iridium NEXT"

satellites_df = pd.concat(
    [
        oneweb_df,
        starlink_df,
        iridium_df
    ],
    ignore_index=True
)

satellites_df.head()

,OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT,CONSTELLATION
0,ONEWEB-0012,2019-010A,2026-09-15T07:25:47.057088,13.165933,0.000248,87.9136,210.8870,85.9127,274.2287,0,U,44057,999,36342,0.000265,1.140000e-06,0.0,OneWeb
1,ONEWEB-0010,2019-010B,2026-09-15T20:48:18.667872,13.165932,0.000192,87.9148,210.7767,69.8134,290.3202,0,U,44058,999,36354,0.000187,8.400000e-07,0.0,OneWeb
2,ONEWEB-0008,2019-010C,2026-09-15T14:07:03.123840,13.165935,0.000191,87.9146,210.8262,90.5607,269.5743,0,U,44059,999,36362,-0.000094,-2.300000e-07,0.0,OneWeb
3,ONEWEB-0007,2019-010D,2026-09-15T22:09:34.634592,13.155480,0.000221,87.8974,241.1262,79.7005,280.4375,0,U,44060,999,36330,-0.000042,-3.000000e-08,0.0,OneWeb
4,ONEWEB-0006,2019-010E,2026-09-15T22:15:15.706368,13.155502,0.000184,87.8984,241.0992,83.6540,276.4800,0,U,44061,999,36335,0.000107,5.300000e-07,0.0,OneWeb

In [8]:
satellites_df.to_csv(
    "data/leo_constellations.csv",
    index=False
)

In [9]:
oneweb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651 entries, 0 to 650
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OBJECT_NAME          651 non-null    object
 1   OBJECT_ID            651 non-null    object
 2   EPOCH                651 non-null    object
 3   MEAN_MOTION          651 non-null    float64
 4   ECCENTRICITY         651 non-null    float64
 5   INCLINATION          651 non-null    float64
 6   RA_OF_ASC_NODE       651 non-null    float64
 7   ARG_OF_PERICENTER    651 non-null    float64
 8   MEAN_ANOMALY         651 non-null    float64
 9   EPHEMERIS_TYPE       651 non-null    int64
 10  CLASSIFICATION_TYPE  651 non-null    object
 11  NORAD_CAT_ID         651 non-null    int64
 12  ELEMENT_SET_NO       651 non-null    int64
 13  REV_AT_EPOCH         651 non-null    int64
 14  BSTAR                651 non-null    float64
 15  MEAN_MOTION_DOT      651 non-null    float64
 16  MEAN_MOTION_DDOT     651 non-null    int64
 17  CONSTELLATION        651 non-null    object
dtypes: float64(8), int64(5), object(5)
memory usage: 91.7+ KB

In [10]:
oneweb_df.isna().sum()

OBJECT_NAME            0
OBJECT_ID              0
EPOCH                  0
MEAN_MOTION            0
ECCENTRICITY           0
INCLINATION            0
RA_OF_ASC_NODE         0
ARG_OF_PERICENTER      0
MEAN_ANOMALY           0
EPHEMERIS_TYPE         0
CLASSIFICATION_TYPE    0
NORAD_CAT_ID           0
ELEMENT_SET_NO         0
REV_AT_EPOCH           0
BSTAR                  0
MEAN_MOTION_DOT        0
MEAN_MOTION_DDOT       0
CONSTELLATION          0
dtype: int64

In [11]:
satellites_df.isna().sum()

OBJECT_NAME            0
OBJECT_ID              0
EPOCH                  0
MEAN_MOTION            0
ECCENTRICITY           0
INCLINATION            0
RA_OF_ASC_NODE         0
ARG_OF_PERICENTER      0
MEAN_ANOMALY           0
EPHEMERIS_TYPE         0
CLASSIFICATION_TYPE    0
NORAD_CAT_ID           0
ELEMENT_SET_NO         0
REV_AT_EPOCH           0
BSTAR                  0
MEAN_MOTION_DOT        0
MEAN_MOTION_DDOT       0
CONSTELLATION          0
dtype: int64

In [12]:
# need to get lat info